Squashed commit of the following:
commit 453cdbfb03e470c403ac63d2bddced8050516f7b
Merge: e754a05 582857d
Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
Date:   Thu Jun 19 06:51:49 2025 +0900

    Merge branch 'develop_example' into develop

commit 582857d4c7fc537d14deba85e1d5cf1dd683de8d
Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
Date:   Thu Jun 19 06:41:00 2025 +0900

    The following warnings have been addressed:
    ```
    example.c: In function ‘main’:
    example.c:14:5: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
       14 |     printf("The example completed successfully.\n");
          |     ^~~~~~
    example.c:2:1: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
        1 | #include "mpfi_legendre_polynomial.h"
      +++ |+#include <stdio.h>
        2 |
    example.c:14:5: warning: incompatible implicit declaration of built-in function ‘printf’ [-Wbuiltin-declaration-mismatch]
       14 |     printf("The example completed successfully.\n");
          |     ^~~~~~
    example.c:14:5: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
    ```

commit 7b05bf136e09ba87ffd0eb880360ff05d096200d
Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
Date:   Thu Jun 19 00:49:57 2025 +0900

    Squashed commit of the following:

    commit e754a05e4ec774b9f8bb1f2d5c7b6efa77a97821
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Thu Jun 19 00:42:09 2025 +0900

        Squashed commit of the following:

        commit 3f3b59e44ca7bf0e0e4860bd7178b0793ab07ce9
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Thu Jun 19 00:39:45 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit 05aca91b698f31a0f19b5516412d4a079c468f3f
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Thu Jun 19 00:09:27 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit d52e60b1569b4c918e0af8bb836999e5019890af
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:43:37 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit 1871fa208fd14e00b95bef4250486087f2e49e34
        Merge: d2abdce 8650020
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:20:05 2025 +0900

            Merge branch 'develop' into develop_workflow

        commit d2abdce350f2383c5420084bf81bed394aba5cf2
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:36:13 2025 +0900

            Fix & Update the workflows
            Add step to install MPFI

        commit 26959478b726c49b531b461c1cc3334fa9e42989
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:25:46 2025 +0900

            Update workflow to run the example

        commit b7eca3f5868be131e677abebc498bb8251438983
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:20:34 2025 +0900

            Add order between workflows

        commit 5ff80217a6a57c9900744f0f4c18237c0c79b9c3
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:23:54 2025 +0900

            Add a workflow to compile & run the example

        commit eb3b67263107c87ecf2c04475f48712ebc5c65d4
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:08:17 2025 +0900

            Add example file

    commit 7a02d1f1d4e9afab080179f96ee7734b20e564b7
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Thu Jun 19 00:29:05 2025 +0900

        Squashed commit of the following:

        commit 05aca91b698f31a0f19b5516412d4a079c468f3f
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Thu Jun 19 00:09:27 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit d52e60b1569b4c918e0af8bb836999e5019890af
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:43:37 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit 1871fa208fd14e00b95bef4250486087f2e49e34
        Merge: d2abdce 8650020
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:20:05 2025 +0900

            Merge branch 'develop' into develop_workflow

        commit d2abdce350f2383c5420084bf81bed394aba5cf2
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:36:13 2025 +0900

            Fix & Update the workflows
            Add step to install MPFI

        commit 26959478b726c49b531b461c1cc3334fa9e42989
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:25:46 2025 +0900

            Update workflow to run the example

        commit b7eca3f5868be131e677abebc498bb8251438983
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:20:34 2025 +0900

            Add order between workflows

        commit 5ff80217a6a57c9900744f0f4c18237c0c79b9c3
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:23:54 2025 +0900

            Add a workflow to compile & run the example

        commit eb3b67263107c87ecf2c04475f48712ebc5c65d4
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:08:17 2025 +0900

            Add example file

    commit 7ce69ae1b8f8c250ee2af57596da7d78b48a5cfa
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 22:56:25 2025 +0900

        Squashed commit of the following:

        commit d52e60b1569b4c918e0af8bb836999e5019890af
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:43:37 2025 +0900

            Fix the workflow to deploy GitHub Pages

        commit 1871fa208fd14e00b95bef4250486087f2e49e34
        Merge: d2abdce 8650020
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 22:20:05 2025 +0900

            Merge branch 'develop' into develop_workflow

        commit d2abdce350f2383c5420084bf81bed394aba5cf2
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:36:13 2025 +0900

            Fix & Update the workflows
            Add step to install MPFI

        commit 26959478b726c49b531b461c1cc3334fa9e42989
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:25:46 2025 +0900

            Update workflow to run the example

        commit b7eca3f5868be131e677abebc498bb8251438983
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:20:34 2025 +0900

            Add order between workflows

        commit 5ff80217a6a57c9900744f0f4c18237c0c79b9c3
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:23:54 2025 +0900

            Add a workflow to compile & run the example

        commit eb3b67263107c87ecf2c04475f48712ebc5c65d4
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:08:17 2025 +0900

            Add example file

    commit 865002066d163ba47d0bde351744bfb878aa6593
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 06:58:07 2025 +0900

        Squashed commit of the following:

        commit 54d2e8d514fc74f063c55fba000c65e2c3d9dc15
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 06:46:04 2025 +0900

            Squashed commit of the following:

            commit d2abdce350f2383c5420084bf81bed394aba5cf2
            Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
            Date:   Wed Jun 18 06:36:13 2025 +0900

                Fix & Update the workflows
                Add step to install MPFI

            commit 26959478b726c49b531b461c1cc3334fa9e42989
            Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
            Date:   Wed Jun 18 06:25:46 2025 +0900

                Update workflow to run the example

            commit b7eca3f5868be131e677abebc498bb8251438983
            Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
            Date:   Wed Jun 18 06:20:34 2025 +0900

                Add order between workflows

            commit 5ff80217a6a57c9900744f0f4c18237c0c79b9c3
            Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
            Date:   Wed Jun 18 00:23:54 2025 +0900

                Add a workflow to compile & run the example

        commit eb3b67263107c87ecf2c04475f48712ebc5c65d4
        Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
        Date:   Wed Jun 18 00:08:17 2025 +0900

            Add example file

commit 54d2e8d514fc74f063c55fba000c65e2c3d9dc15
Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
Date:   Wed Jun 18 06:46:04 2025 +0900

    Squashed commit of the following:

    commit d2abdce350f2383c5420084bf81bed394aba5cf2
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 06:36:13 2025 +0900

        Fix & Update the workflows
        Add step to install MPFI

    commit 26959478b726c49b531b461c1cc3334fa9e42989
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 06:25:46 2025 +0900

        Update workflow to run the example

    commit b7eca3f5868be131e677abebc498bb8251438983
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 06:20:34 2025 +0900

        Add order between workflows

    commit 5ff80217a6a57c9900744f0f4c18237c0c79b9c3
    Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
    Date:   Wed Jun 18 00:23:54 2025 +0900

        Add a workflow to compile & run the example

commit eb3b67263107c87ecf2c04475f48712ebc5c65d4
Author: DSCF-1224 <37315588+DSCF-1224@users.noreply.github.com>
Date:   Wed Jun 18 00:08:17 2025 +0900

    Add example file